const periodTypeSelect = document.getElementById('periodTypeSelect');
const periodSelect = document.getElementById('periodSelect');
const techSelect = document.getElementById('techSelect');
const generate = document.getElementById('generate');
const exportCsv = document.getElementById('exportCsv');
const pageTitle = document.getElementById('pageTitle');
const pageIntro = document.getElementById('pageIntro');
const deviceNum = document.getElementById('deviceNum');
const periodLabel = document.getElementById('periodLabel');
const kQuotes = document.getElementById('kQuotes');
const kConversion = document.getElementById('kConversion');
const kRevenue = document.getElementById('kRevenue');
const kEgp = document.getElementById('kEgp');
const techNameKpi = document.getElementById('techNameKpi');
const techAttKpi = document.getElementById('techAttKpi');
const techQuoteKpi = document.getElementById('techQuoteKpi');
const techValueKpi = document.getElementById('techValueKpi');

const fmtMoney=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n||0);
const fmtNum=n=>new Intl.NumberFormat('en-AU',{maximumFractionDigits:0}).format(n||0);
const fmtPct=n=>`${((n||0)*100).toFixed(1)}%`;
const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(d,days)=>{const x=new Date(d);x.setDate(x.getDate()+days);return x};
const labelDate=d=>d.toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'});
const labelWeek=w=>`${labelDate(parseDate(w))} – ${labelDate(addDays(parseDate(w),6))}`;
const allWeeks=[...new Set(QUOTES_DATA.map(d=>d.week))].sort();
const techNames=[...new Set(TECH_DATA.map(d=>d.technician))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
const years=[...new Set(allWeeks.map(w=>parseDate(w).getFullYear()))].sort();
const months=[...new Set(allWeeks.map(w=>w.slice(0,7)))].sort();
const seasons={Summer:[12,1,2],Autumn:[3,4,5],Winter:[6,7,8],Spring:[9,10,11]};
const lossReasons=['Price','No response','Competitor awarded','Scope changed','Timing','Budget deferred'];
const TARGET_QUOTE_RATE=.30, TARGET_MAINT_RATE=.16;
function seeded(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24)}return Math.abs(h>>>0)/4294967295}
function monthLabel(m){return new Date(m+'-01').toLocaleDateString('en-AU',{month:'long',year:'numeric'})}
function getPeriods(type){
  if(type==='Weekly') return allWeeks.map(w=>({label:labelWeek(w),value:`week:${w}`,weeks:[w],sort:w})).reverse();
  if(type==='Monthly') return months.map(m=>({label:monthLabel(m),value:`month:${m}`,weeks:allWeeks.filter(w=>w.slice(0,7)===m),sort:m})).reverse();
  if(type==='4-Weekly'){let out=[]; for(let i=allWeeks.length-1;i>=0;i-=4){const s=Math.max(0,i-3),e=i,weeks=allWeeks.slice(s,e+1);out.push({label:`${labelDate(parseDate(weeks[0]))} – ${labelDate(addDays(parseDate(weeks[weeks.length-1]),6))}`,value:`block:${s}:${e}`,weeks,sort:weeks[0]})} return out;}
  if(type==='Seasonally'){let out=[]; years.slice().reverse().forEach(y=>['Summer','Autumn','Winter','Spring'].forEach(season=>{const weeks=allWeeks.filter(w=>String(parseDate(w).getFullYear())===String(y)&&seasons[season].includes(parseDate(w).getMonth()+1)); if(weeks.length) out.push({label:`${season} ${y}`,value:`season:${y}:${season}`,weeks,sort:`${y}-${season}`})})); return out;}
  return years.slice().reverse().map(y=>({label:String(y),value:`year:${y}`,weeks:allWeeks.filter(w=>String(parseDate(w).getFullYear())===String(y)),sort:String(y)}));
}
function fillPeriods(keep){const old=periodSelect.value; periodSelect.innerHTML=''; const periods=getPeriods(periodTypeSelect.value); periods.forEach(p=>periodSelect.add(new Option(p.label,p.value))); if(keep&&[...periodSelect.options].some(o=>o.value===old)){periodSelect.value=old}else if(periods.length){periodSelect.value=periods[0].value}}
function selectedWeeks(){const found=getPeriods(periodTypeSelect.value).find(p=>p.value===periodSelect.value);return found?found.weeks:allWeeks.slice(-1)}
function init(){techNames.forEach(t=>techSelect.add(new Option(t,t)));fillPeriods(false);document.querySelectorAll('#mainNav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));periodTypeSelect.onchange=()=>{fillPeriods(false);update()};[periodSelect,techSelect].forEach(el=>el.addEventListener('change',update));generate.onclick=update;exportCsv.onclick=downloadCsv;update();}
function showPage(page){document.querySelectorAll('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));const titles={overview:['Executive Overview','Headline performance across quoting, margin and technician activity.','01'],quotes:['Quote Activity','Quote volume, ageing, revenue and weekly detail.','02'],technicians:['Technician Performance','Period-by-period technician management view with peer benchmarks and coaching signals.','03'],margins:['Margins & Win Rate','Average EGP, target tracking and conversion quality.','04'],losses:['Loss Reasons','Quote losses by reason, count, value and share.','05']};pageTitle.textContent=titles[page][0];pageIntro.textContent=titles[page][1];deviceNum.textContent=titles[page][2];}
function aggregateQuotes(rows){return rows.reduce((a,r)=>{a.created+=r.created_count||0;a.won+=r.won_count||0;a.createdValue+=r.created_value||0;a.wonValue+=r.won_value||0;a.pending+=r.pending_count||0;a.a0+=r.age_0_7||0;a.a1+=r.age_8_14||0;a.a2+=r.age_15_30||0;a.a3+=r.age_31_plus||0;a.egpAll+=(r.avg_gross_margin_created||0)*(r.created_count||0);a.egpWon+=(r.avg_gross_margin_won||0)*(r.won_count||0);return a},{created:0,won:0,createdValue:0,wonValue:0,pending:0,a0:0,a1:0,a2:0,a3:0,egpAll:0,egpWon:0})}
function techAgg(rows){const m={};rows.forEach(r=>{const t=r.technician;if(!m[t])m[t]={technician:t,att:0,quotes:0,value:0,egpW:0,maintHours:0,maintJobs:0};m[t].att+=r.attendances||0;m[t].quotes+=r.quotes_generated||0;m[t].value+=r.total_value||0;m[t].egpW+=(r.avg_nett_egp||0)*(r.quotes_generated||0);m[t].maintHours+=r.maint_hours||0;m[t].maintJobs+=r.maint_jobs_attended||0});return Object.values(m).map(x=>({...x,ratio:x.att?x.quotes/x.att:0,maintRatio:x.maintJobs?x.quotes/x.maintJobs:0,hourRatio:x.maintHours?x.quotes/x.maintHours:0,egp:x.quotes?x.egpW/x.quotes:0}))}
function update(){const weeks=selectedWeeks();const qRows=QUOTES_DATA.filter(r=>weeks.includes(r.week));let tRows=TECH_DATA.filter(r=>weeks.includes(r.week));if(techSelect.value!=='All technicians')tRows=tRows.filter(r=>r.technician===techSelect.value);const q=aggregateQuotes(qRows);kQuotes.textContent=fmtNum(q.created);kConversion.textContent=fmtPct(q.created?q.won/q.created:0);kRevenue.textContent=fmtMoney(q.wonValue);kEgp.textContent=fmtPct(q.won?q.egpWon/q.won:0);const activePeriod=getPeriods(periodTypeSelect.value).find(p=>p.value===periodSelect.value);periodLabel.textContent=activePeriod?activePeriod.label:(weeks.length?`${labelDate(parseDate(weeks[0]))} – ${labelDate(addDays(parseDate(weeks[weeks.length-1]),6))}`:'No data');renderAll(qRows,tRows,q)}
function renderAll(qRows,tRows,q){const techs=techAgg(tRows).sort((a,b)=>b.value-a.value);barLine('chartQuoteValue',qRows.slice(-24).map(r=>({label:r.week.slice(5),bar:r.created_value,line:r.won_value})),'$ Total','$ Won');lineChart('chartWinRate',qRows.slice(-52).map(r=>({label:r.week.slice(5),v:r.created_count?r.won_count/r.created_count:0})),0,1,false,.55,'55% target');egpChart('chartEgpOverview',qRows.slice(-52).map(r=>({label:r.week.slice(5),a:r.avg_gross_margin_created,w:r.avg_gross_margin_won})));donut('chartVolumeMix',[['Won',q.won],['Pending',q.pending],['Lost/Other',Math.max(q.created-q.won-q.pending,0)]]);barLine('chartQuoteCount',qRows.slice(-30).map(r=>({label:r.week.slice(5),bar:r.created_count,line:r.won_count})),'Raised','Won');hbar('chartAgeing',[['0–7 days',q.a0],['8–14 days',q.a1],['15–30 days',q.a2],['31+ days',q.a3]]);table('quoteTable',['Week','Raised','Won','Conversion','Quoted $','Won $','Avg EGP'],qRows.slice().reverse().map(r=>[labelWeek(r.week),r.created_count,r.won_count,fmtPct(r.created_count?r.won_count/r.created_count:0),fmtMoney(r.created_value),fmtMoney(r.won_value),fmtPct(r.avg_gross_margin_won)]));renderTechPage(tRows,techs);egpChart('chartEgp',qRows.map(r=>({label:r.week.slice(5),a:r.avg_gross_margin_created,w:r.avg_gross_margin_won})));lineChart('chartWinCountValue',qRows.map(r=>({label:r.week.slice(5),v:r.created_count?r.won_count/r.created_count:0,v2:r.created_value?r.won_value/r.created_value:0})),0,1,true,.55,'55% target');table('marginTable',['Technician','Quotes','Quoted $','Average Nett EGP','Target Gap'],techs.map(t=>[t.technician,fmtNum(t.quotes),fmtMoney(t.value),fmtPct(t.egp),fmtPct(t.egp-.55)]));const losses=lossData(qRows);hbar('chartLossReasons',losses.map(x=>[x.reason,x.count]));hbar('chartLostValue',losses.map(x=>[x.reason,x.value]),true);const totalLoss=losses.reduce((s,x)=>s+x.count,0);table('lossTable',['Reason','Count','Share','Lost $','Average $'],losses.map(x=>[x.reason,x.count,fmtPct(totalLoss?x.count/totalLoss:0),fmtMoney(x.value),fmtMoney(x.count?x.value/x.count:0)]))}
function periodSummaryRows(){return getPeriods(periodTypeSelect.value).map(p=>{const rows=TECH_DATA.filter(r=>p.weeks.includes(r.week));const a=techAgg(rows).reduce((x,t)=>({att:x.att+t.att,quotes:x.quotes+t.quotes,maintJobs:x.maintJobs+t.maintJobs,maintHours:x.maintHours+t.maintHours,value:x.value+t.value}),{att:0,quotes:0,maintJobs:0,maintHours:0,value:0});return {p,...a,ratio:a.att?a.quotes/a.att:0,maintRatio:a.maintJobs?a.quotes/a.maintJobs:0}})}
function renderTechPage(tRows,techs){const totals=techs.reduce((a,t)=>({att:a.att+t.att,quotes:a.quotes+t.quotes,value:a.value+t.value,maintJobs:a.maintJobs+t.maintJobs,maintHours:a.maintHours+t.maintHours}),{att:0,quotes:0,value:0,maintJobs:0,maintHours:0});techNameKpi.textContent=techSelect.value==='All technicians'?'All techs':techSelect.value;techAttKpi.textContent=fmtNum(totals.att);techQuoteKpi.textContent=fmtNum(totals.quotes);techValueKpi.textContent=fmtMoney(totals.value);
  const periods=periodSummaryRows();table('periodSummaryTable',[periodTypeSelect.value==='Weekly'?'Week':'Period','Attendances','Maintenance Attendances','Quotes','Quote Rate','Maint Attend/Quote','Maint Hours','Quoted $'],periods.map(x=>[x.p.label,fmtNum(x.att),fmtNum(x.maintJobs),fmtNum(x.quotes),fmtPct(x.ratio),x.quotes?(x.maintJobs/x.quotes).toFixed(1):'—',x.maintHours.toFixed(1),fmtMoney(x.value)]),(row,i)=>{periodSelect.value=periods[i].p.value;update();showPage('technicians')});
  const allForBenchmark=techAgg(TECH_DATA.filter(r=>selectedWeeks().includes(r.week))).sort((a,b)=>b.ratio-a.ratio);const avgRatio=allForBenchmark.reduce((s,t)=>s+t.quotes,0)/Math.max(allForBenchmark.reduce((s,t)=>s+t.att,0),1);const avgMaint=allForBenchmark.reduce((s,t)=>s+t.quotes,0)/Math.max(allForBenchmark.reduce((s,t)=>s+t.maintJobs,0),1);benchmarkBar('chartTechRatio',allForBenchmark.map(t=>[t.technician,t.ratio]),avgRatio,TARGET_QUOTE_RATE,'Team avg','Target');benchmarkBar('chartMaintRatio',allForBenchmark.sort((a,b)=>b.maintRatio-a.maintRatio).map(t=>[t.technician,t.maintRatio]),avgMaint,TARGET_MAINT_RATE,'Team avg','Target');
  const trend=buildTrend(tRows);barLine('chartTechDetail',trend.map(w=>({label:w.label,bar:w.att,line:w.quotes})),'Attendances','Quotes');funnel('chartTopTechs',[['Maintenance attendances',totals.maintJobs],['Quotes written',totals.quotes],['Quotes won est.',Math.round(totals.quotes*.58)]]);
  table('techWeeklyTable',['Technician','Attendances','Maintenance Attended','Quotes Written','Maintenance Hours','Maint Attend/Quote','Quote Rate','Quoted $','Avg EGP','Decision Signal'],techs.sort((a,b)=>b.ratio-a.ratio).map(t=>[t.technician,fmtNum(t.att),fmtNum(t.maintJobs),fmtNum(t.quotes),t.maintHours.toFixed(1),t.quotes?(t.maintJobs/t.quotes).toFixed(1):'—',fmtPct(t.ratio),fmtMoney(t.value),fmtPct(t.egp),t.ratio>=TARGET_QUOTE_RATE?'Above target':(t.ratio>=avgRatio?'Above team avg':'Needs review')]));
  table('techTable',['Technician','Attendances','Quotes','Quote Rate','Maint Attended','Maint Attend/Quote','Maint Hours','Quote/Maint Hr','Quoted $','Avg EGP'],techs.map(t=>[t.technician,fmtNum(t.att),fmtNum(t.quotes),fmtPct(t.ratio),fmtNum(t.maintJobs),t.quotes?(t.maintJobs/t.quotes).toFixed(1):'—',t.maintHours.toFixed(1),t.hourRatio.toFixed(3),fmtMoney(t.value),fmtPct(t.egp)]),row=>{techSelect.value=row[0];update();showPage('technicians')})}
function buildTrend(rows){const map={};rows.forEach(r=>{const key=periodTypeSelect.value==='Weekly'?r.week:periodTypeSelect.value==='Monthly'?r.week.slice(0,7):periodTypeSelect.value==='Yearly'?String(parseDate(r.week).getFullYear()):periodTypeSelect.value==='Seasonally'?`${parseDate(r.week).getFullYear()} ${Object.keys(seasons).find(s=>seasons[s].includes(parseDate(r.week).getMonth()+1))}`:r.week;if(!map[key])map[key]={label:key.length===10?key.slice(2,10):key,att:0,quotes:0};map[key].att+=r.attendances||0;map[key].quotes+=r.quotes_generated||0});return Object.values(map).slice(-60)}
function lossData(qRows){const totals={};lossReasons.forEach(r=>totals[r]={reason:r,count:0,value:0});qRows.forEach(q=>{let lost=Math.max(q.created_count-q.won_count-q.pending_count,0)+Math.round((q.pending_count||0)*.35);lossReasons.forEach(reason=>{const p=.08+seeded(q.week+reason)*.25;const c=Math.round(lost*p);totals[reason].count+=c;totals[reason].value+=c*((q.created_value||0)/Math.max(q.created_count||1,1))*(.75+seeded(reason+q.week)*.8)})});return Object.values(totals).sort((a,b)=>b.count-a.count)}
function svgWrap(id,content,h=360){const el=document.getElementById(id);if(el)el.innerHTML=`<svg viewBox="0 0 900 ${h}" preserveAspectRatio="xMidYMid meet">${content}</svg>`}
function lineChart(id,data,min=0,max=null,two=false,target=null,targetLabel='Target'){if(!data.length)return svgWrap(id,'');max=max??Math.max(...data.flatMap(d=>[d.v,d.v2||0]),.01);const W=900,H=360,L=76,R=34,T=34,B=58,plotW=W-L-R,plotH=H-T-B;const x=i=>L+(data.length<=1?0:i*plotW/(data.length-1));const y=v=>T+plotH-(v-min)/(max-min)*plotH;let c=`<line class="axis" x1="${L}" x2="${W-R}" y1="${T+plotH}" y2="${T+plotH}"/>`;if(target!==null){c+=`<line class="target" x1="${L}" x2="${W-R}" y1="${y(target)}" y2="${y(target)}"/><text class="value-label" x="${W-R-130}" y="${y(target)-8}">${targetLabel}</text>`}const path=vals=>vals.map((d,i)=>(i?'L':'M')+x(i)+' '+y(d)).join(' ');c+=`<path class="line1" d="${path(data.map(d=>d.v))}"/>`;if(two)c+=`<path class="line2" d="${path(data.map(d=>d.v2||0))}"/>`;c+=`<text class="legend" x="${L}" y="${H-18}">${data[0].label}</text><text class="legend" x="${W-R-120}" y="${H-18}">${data[data.length-1].label}</text>`;svgWrap(id,c,H)}
function egpChart(id,data){lineChart(id,data.map(d=>({label:d.label,v:d.w||0,v2:d.a||0})),0,.8,true,.55,'55% target')}
function barLine(id,data,barLabel,lineLabel){if(!data.length)return svgWrap(id,'');const W=900,H=360,L=76,R=34,T=36,B=58,plotW=W-L-R,plotH=H-T-B;const max=Math.max(...data.flatMap(d=>[d.bar,d.line]),1);const bw=Math.max(4,plotW/data.length*.58);const x=i=>L+i*plotW/data.length+plotW/data.length*.2;const y=v=>T+plotH-v/max*plotH;let c=`<line class="axis" x1="${L}" x2="${W-R}" y1="${T+plotH}" y2="${T+plotH}"/>`;data.forEach((d,i)=>c+=`<rect class="bar" x="${x(i)}" y="${y(d.bar)}" width="${bw}" height="${T+plotH-y(d.bar)}" rx="3"/>`);c+=`<path class="line2" d="${data.map((d,i)=>(i?'L':'M')+(x(i)+bw/2)+' '+y(d.line)).join(' ')}"/>`;c+=`<text class="legend" x="${L}" y="22">${barLabel}</text><text class="legend" x="${L+150}" y="22">${lineLabel}</text><text class="legend" x="${L}" y="${H-18}">${data[0].label}</text><text class="legend" x="${W-R-120}" y="${H-18}">${data[data.length-1].label}</text>`;svgWrap(id,c,H)}
function hbar(id,items,money=false){if(!items.length)return svgWrap(id,'');const W=900,H=360,L=220,R=120,T=24,B=24,plotW=W-L-R,rowH=(H-T-B)/items.length;const max=Math.max(...items.map(x=>x[1]),1);let c='';items.forEach((it,i)=>{const y=T+i*rowH+5,w=it[1]/max*plotW;c+=`<text class="label" x="12" y="${y+rowH*.55}">${it[0]}</text><rect class="bar" x="${L}" y="${y}" width="${w}" height="${Math.max(8,rowH-10)}" rx="5"/><text class="value-label" x="${Math.min(L+w+10,W-150)}" y="${y+rowH*.55}">${money?fmtMoney(it[1]):(it[1]<1?fmtPct(it[1]):fmtNum(it[1]))}</text>`});svgWrap(id,c,H)}
function benchmarkBar(id,items,avg,target,avgLabel,targetLabel){if(!items.length)return svgWrap(id,'');const W=900,H=380,L=210,R=70,T=30,B=34,plotW=W-L-R,rowH=(H-T-B)/items.length;const max=Math.max(...items.map(x=>x[1]),target,avg,.01)*1.15;const x=v=>L+v/max*plotW;let c=`<line class="target" x1="${x(target)}" x2="${x(target)}" y1="${T}" y2="${H-B}"/><text class="value-label" x="${x(target)+6}" y="22">${targetLabel} ${fmtPct(target)}</text><line class="avgline" x1="${x(avg)}" x2="${x(avg)}" y1="${T}" y2="${H-B}"/><text class="value-label" x="${x(avg)+6}" y="42">${avgLabel} ${fmtPct(avg)}</text>`;items.forEach((it,i)=>{const y=T+i*rowH+5,w=it[1]/max*plotW;c+=`<text class="label" x="12" y="${y+rowH*.55}">${it[0]}</text><rect class="bar" x="${L}" y="${y}" width="${w}" height="${Math.max(12,rowH-10)}" rx="5"/><text class="value-label" x="${Math.min(L+w+10,W-90)}" y="${y+rowH*.55}">${fmtPct(it[1])}</text>`});svgWrap(id,c,H)}
function funnel(id,items){const W=900,H=380,L=120,T=56;const max=Math.max(...items.map(x=>x[1]),1);let c='';items.forEach((it,i)=>{const w=620*(it[1]/max),x=L+(620-w)/2,y=T+i*96;c+=`<rect class="bar" x="${x}" y="${y}" width="${w}" height="54" rx="10"/><text class="label" x="${L+650}" y="${y+32}">${it[0]}</text><text class="value-label" x="${x+w/2-18}" y="${y+34}">${fmtNum(it[1])}</text>`;if(i<items.length-1)c+=`<text class="legend" x="${L+300}" y="${y+82}">↓</text>`});svgWrap(id,c,H)}
function donut(id,items){const total=items.reduce((s,x)=>s+x[1],0)||1;let x=220,y=180,r=105,circ=2*Math.PI*r,off=0,c='';items.forEach((it,i)=>{const frac=it[1]/total;c+=`<circle cx="${x}" cy="${y}" r="${r}" fill="none" stroke="${i==0?'#2C5F7C':i==1?'#E87722':'#d6a87c'}" stroke-width="54" stroke-dasharray="${frac*circ} ${circ}" stroke-dashoffset="${-off}" transform="rotate(-90 ${x} ${y})"/>`;off+=frac*circ});c+=`<circle cx="${x}" cy="${y}" r="68" fill="white"/><text class="value-label" x="${x-30}" y="${y+5}">${fmtNum(total)}</text>`;items.forEach((it,i)=>c+=`<rect x="480" y="${110+i*54}" width="22" height="22" rx="4" fill="${i==0?'#2C5F7C':i==1?'#E87722':'#d6a87c'}"/><text class="legend" x="516" y="${128+i*54}">${it[0]} · ${fmtNum(it[1])}</text>`);svgWrap(id,c,360)}
function table(id,headers,rows,onClick){const el=document.getElementById(id);if(!el)return;el.innerHTML='<thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map((r,i)=>`<tr data-i="${i}">`+r.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')+'</tbody>';if(onClick)el.querySelectorAll('tbody tr').forEach(tr=>tr.onclick=()=>onClick(rows[+tr.dataset.i],+tr.dataset.i))}
function downloadCsv(){const weeks=selectedWeeks();const rows=TECH_DATA.filter(r=>weeks.includes(r.week));const csv=[Object.keys(rows[0]||{}).join(',')].concat(rows.map(r=>Object.values(r).join(','))).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='paramount_technician_period_report.csv';a.click()}
init();
